# -*- coding: utf-8 -*-
"""YouTube Analytics Project using Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ej5Pq392CIWsl0R_fsa3ErNAcAooX91
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset using the path from your upload
df = pd.read_csv('/content/Global YouTube Statistics (1).csv', encoding='latin-1')
display(df.head())

# 1. Which YouTube channels have the highest number of subscribers?

top_subscribers = df[['Youtuber', 'subscribers']].sort_values(by='subscribers', ascending=False).head(10)
print("Top 10 Channels by Subscribers:")
display(top_subscribers)

# 2. Which channels have the highest video views?

top_views = df[['Youtuber', 'video views']].sort_values(by='video views', ascending=False).head(10)
print("\nTop 10 Channels by Video Views:")
display(top_views)

# 3. Which countries have the highest number of YouTube creators?

top_countries = df['Country'].value_counts().head(10)
print("\nTop 10 Countries by Number of Creators:")
display(top_countries)

# Visualizing the findings
plt.figure(figsize=(15, 5))

# Subscribers Plot
plt.subplot(1, 3, 1)
sns.barplot(x='subscribers', y='Youtuber', data=top_subscribers, palette='deep')
plt.title('Top 10 by Subscribers')

# Views Plot
plt.subplot(1, 3, 2)
sns.barplot(x='video views', y='Youtuber', data=top_views, palette='magma')
plt.title('Top 10 by Video Views')

# Country Plot
plt.subplot(1, 3, 3)
top_countries.plot(kind='bar', color='skyblue')
plt.title('Top 10 Countries')
plt.ylabel('Count')

plt.tight_layout()
plt.show()